// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type BackendExpansion interface{}

type BackendTrafficPolicyExpansion interface{}

type ClientTrafficPolicyExpansion interface{}

type EnvoyExtensionPolicyExpansion interface{}

type EnvoyPatchPolicyExpansion interface{}

type EnvoyProxyExpansion interface{}

type HTTPRouteFilterExpansion interface{}

type SecurityPolicyExpansion interface{}
